// examples/react/src/App.tsx
import { useState } from 'react';

type Task = { id: string; title: string; done: boolean };
type Filter = 'All' | 'Open' | 'Done';
const filters: Filter[] = ['All', 'Open', 'Done'];

export function App() {
  const [tasks, setTasks] = useState<Task[]>([
    { id: 'brief', title: 'Review the project brief', done: true },
    { id: 'sketch', title: 'Sketch the onboarding flow', done: false },
    { id: 'feedback', title: 'Collect feedback from the team', done: false },
  ]);
  const [title, setTitle] = useState('');
  const [filter, setFilter] = useState<Filter>('All');
  const remaining = tasks.filter((task) => !task.done).length;
  const visible = tasks.filter((task) => filter === 'All' || task.done === (filter === 'Done'));

  return (
    <main>
      <header>
        <p className="eyebrow">Studio / Project planner</p>
        <h1>
          A little progress,
          <br />
          every day.
        </h1>
        <p>Keep the next steps in sight. Make room for the work that matters.</p>
      </header>
      <section aria-label="Task board" className="panel">
        <div className="section-heading">
          <h2>This week's work</h2>
          <p role="status">
            {remaining} {remaining === 1 ? 'task' : 'tasks'} remaining
          </p>
        </div>
        <form
          onSubmit={(event) => {
            event.preventDefault();
            const trimmed = title.trim();
            if (!trimmed) return;
            setTasks((current) => [
              ...current,
              { id: crypto.randomUUID(), title: trimmed, done: false },
            ]);
            setTitle('');
          }}
        >
          <label className="grow">
            New task
            <input
              value={title}
              onChange={(event) => setTitle(event.target.value)}
              placeholder="What needs to happen next?"
              maxLength={120}
            />
          </label>
          <button type="submit" disabled={!title.trim()}>
            Add task
          </button>
        </form>
        <nav aria-label="Filter tasks" className="filters">
          {filters.map((value) => (
            <button
              key={value}
              type="button"
              aria-pressed={filter === value}
              onClick={() => setFilter(value)}
            >
              {value}
            </button>
          ))}
        </nav>
        <ul className="items">
          {visible.map((task) => (
            <li key={task.id}>
              <label className="task-label">
                <input
                  type="checkbox"
                  checked={task.done}
                  onChange={() =>
                    setTasks((current) =>
                      current.map((item) =>
                        item.id === task.id ? { ...item, done: !item.done } : item,
                      ),
                    )
                  }
                />
                <span className={task.done ? 'completed' : ''}>{task.title}</span>
              </label>
              <button
                className="quiet"
                type="button"
                aria-label={`Delete ${task.title}`}
                onClick={() => setTasks((current) => current.filter((item) => item.id !== task.id))}
              >
                Delete
              </button>
            </li>
          ))}
        </ul>
        {visible.length === 0 ? (
          <p className="empty">
            No {filter === 'All' ? '' : filter.toLowerCase() + ' '}tasks. A clean slate.
          </p>
        ) : null}
      </section>
      <footer>Changes stay in this session. Refresh to start again.</footer>
    </main>
  );
}

// examples/solid/src/App.tsx
import { createMemo, createSignal, For, Show } from 'solid-js';

const categories = ['Food', 'Travel', 'Stay'] as const;
type Category = (typeof categories)[number];
type Expense = { id: string; description: string; cents: number; category: Category };
const money = (cents: number) =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'EUR' }).format(cents / 100);

export function App() {
  const [expenses, setExpenses] = createSignal<Expense[]>([
    { id: 'train', description: 'Train to Copenhagen', cents: 4800, category: 'Travel' },
    { id: 'lunch', description: 'Lunch at the market', cents: 1850, category: 'Food' },
  ]);
  const [description, setDescription] = createSignal('');
  const [amount, setAmount] = createSignal('');
  const [category, setCategory] = createSignal<Category>('Food');
  const [filter, setFilter] = createSignal<Category | 'All'>('All');
  const visible = createMemo(() =>
    expenses().filter((expense) => filter() === 'All' || expense.category === filter()),
  );
  const total = createMemo(() => visible().reduce((sum, expense) => sum + expense.cents, 0));
  const valid = () =>
    description().trim().length > 0 &&
    /^\d+(\.\d{1,2})?$/.test(amount()) &&
    Number(amount()) > 0 &&
    Number(amount()) <= 100000;

  return (
    <main>
      <header>
        <p class="eyebrow">Travel journal / Copenhagen</p>
        <h1>
          Good trips.
          <br />
          Clear expenses.
        </h1>
        <p>A shared record of the small things that add up.</p>
      </header>
      <section class="panel" aria-label="Expense tracker">
        <div class="section-heading">
          <h2>Trip expenses</h2>
          <p role="status">
            {money(total())} · {visible().length} {visible().length === 1 ? 'expense' : 'expenses'}
          </p>
        </div>
        <form
          onSubmit={(event) => {
            event.preventDefault();
            if (!valid()) return;
            setExpenses((current) => [
              ...current,
              {
                id: crypto.randomUUID(),
                description: description().trim(),
                cents: Math.round(Number(amount()) * 100),
                category: category(),
              },
            ]);
            setDescription('');
            setAmount('');
          }}
        >
          <label class="grow">
            Description
            <input
              value={description()}
              onInput={(event) => setDescription(event.currentTarget.value)}
              placeholder="Coffee by the canal"
              maxLength={120}
            />
          </label>
          <label>
            Amount (EUR)
            <input
              class="amount"
              type="number"
              min="0.01"
              max="100000"
              step="0.01"
              value={amount()}
              onInput={(event) => setAmount(event.currentTarget.value)}
              placeholder="0.00"
            />
          </label>
          <label>
            Category
            <select
              value={category()}
              onChange={(event) => {
                const selected = categories.find((value) => value === event.currentTarget.value);
                if (selected) setCategory(selected);
              }}
            >
              <For each={categories}>{(value) => <option>{value}</option>}</For>
            </select>
          </label>
          <button type="submit" disabled={!valid()}>
            Add expense
          </button>
        </form>
        <nav class="filters" aria-label="Filter expenses">
          <button type="button" aria-pressed={filter() === 'All'} onClick={() => setFilter('All')}>
            All
          </button>
          <For each={categories}>
            {(value) => (
              <button
                type="button"
                aria-pressed={filter() === value}
                onClick={() => setFilter(value)}
              >
                {value}
              </button>
            )}
          </For>
        </nav>
        <ul class="items">
          <For each={visible()}>
            {(expense) => (
              <li>
                <div class="grow">
                  <strong>{expense.description}</strong>
                  <small>{expense.category}</small>
                </div>
                <span class="money">{money(expense.cents)}</span>
                <button
                  class="quiet"
                  type="button"
                  aria-label={`Delete ${expense.description}`}
                  onClick={() =>
                    setExpenses((current) => current.filter((item) => item.id !== expense.id))
                  }
                >
                  Delete
                </button>
              </li>
            )}
          </For>
        </ul>
        <Show when={visible().length === 0}>
          <p class="empty">No expenses in this category yet.</p>
        </Show>
      </section>
      <footer>Amounts are in euros. Changes reset when you refresh.</footer>
    </main>
  );
}
